#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

START=17

start() {
  NEWMAC=$(printf "%02x" $(( $(hexdump -n1 -e'/1 "0x%02x"' /dev/urandom) & ~1 | 2)) && hexdump -n5 -e'/1 ":%02x"' /dev/urandom)
  logger "[LAN-MAC] Applying new random MAC address to LAN (${NEWMAC})..."
  uci set network.@device[0].macaddr=${NEWMAC}

  uci commit network
}
